Approve these changes
SecretBoatDev/SecretBoatDev.github.io pull request #2
Opened 2022-05-14 13:30 UTC by Oakchris1955

I need you guys to review this pull request and edit `about/userinfo.json` to have your info too

2022-05-14 13:37 UTC, 8u83r70 approved these changes
Cum

2022-05-14 13:39 UTC, Oakchris1955 commented
To add yourself to the website, go to `assets/userinfo.json` and add these according to you under `Users`
@LukasDoesDev ,check this out
```json
"_username goes here_": {
	"FirstName": "_first name goes here_",
	"UserIcon": "_the url to your icon goes here_",
	"About": "_add anything you want here_",
	"Connections": {
		"Github": "_add connections here. key is connection name, value is URL/JS code_",
		"Discord": "_you can input as many as you want. if yours doesn't exist, just add it to Icons_"
	}
}
```

2022-05-14 13:52 UTC, splatterxl requested changes

2022-05-14 13:52 UTC, splatterxl commented on about/index.html
> +        <div id="gallery"></div>
make this a semantic `<article>`

2022-05-14 13:52 UTC, splatterxl commented on about/index.html
> +	<script>includeHTML()</script>
don't have this in a function, make it run when the script is started

2022-05-14 13:52 UTC, splatterxl commented on about/userinfo.json
> +{
make these properties snake_case or at least camelCase not PascalCase

2022-05-14 13:52 UTC, splatterxl commented on general/bar.html
> +<a class="item" href="">
can you rename this folder to "_include"

2022-05-14 13:52 UTC, splatterxl commented on init.js
> +function includeHTML() {
ideally this wouldn't be js for older browsers & non-js users

2022-05-14 13:52 UTC, splatterxl commented on init.js
> +			xhttp = new XMLHttpRequest();
use fetch

2022-05-14 13:52 UTC, splatterxl commented on init.js
> +					if (this.status == 404) { elmnt.innerHTML = "Error while loading."; }
use textContent instead of innerHTML

2022-05-14 13:52 UTC, splatterxl commented on init.js
> +					includeHTML();
why are you recursively calling

2022-05-14 13:52 UTC, splatterxl commented on init.js
> +			return;
unnecessary

2022-05-14 13:52 UTC, splatterxl commented on init.js
> +	var z, i, elmnt, file, xhttp;
use verbose names and don't use var

2022-05-14 14:16 UTC, Oakchris1955 commented on about/index.html
> +	<script>includeHTML()</script>
I tried, it wouldn't tho

2022-05-14 14:16 UTC, Oakchris1955 commented on about/userinfo.json
> +{
It is JSON, lol

2022-05-14 14:16 UTC, Oakchris1955 commented on init.js
> +function includeHTML() {
Who uses old browsers?

2022-05-14 14:17 UTC, Oakchris1955 commented on init.js
> +			xhttp = new XMLHttpRequest();
why? This works good as well

2022-05-14 14:17 UTC, Oakchris1955 commented on init.js
> +					includeHTML();
Cuz I made this code like 2 years ago first time and I had to, else it won't work

2022-05-14 14:18 UTC, Oakchris1955 commented on init.js
> +	var z, i, elmnt, file, xhttp;
Don't you want old browser compatibility?

2022-05-14 14:18 UTC, Oakchris1955 commented on init.js
> +			return;
oh, alright, lemme change this

2022-05-14 14:19 UTC, Oakchris1955 commented on init.js
> +			return;
Fixed

2022-05-14 14:20 UTC, Oakchris1955 commented on init.js
> +	var z, i, elmnt, file, xhttp;
Resolved

2022-05-14 14:20 UTC, Oakchris1955 commented on general/bar.html
> +<a class="item" href="">
alright, but approve it @splatterxl

2022-05-14 14:22 UTC, Oakchris1955 commented on general/bar.html
> +<a class="item" href="">
Resolved

2022-05-14 14:23 UTC, splatterxl commented on about/userinfo.json
> +{
wdym

2022-05-14 14:24 UTC, splatterxl commented on init.js
> +function includeHTML() {
a lot of people

2022-05-14 14:24 UTC, splatterxl commented on init.js
> +			xhttp = new XMLHttpRequest();
no, it doesn't

2022-05-14 14:24 UTC, Oakchris1955 commented on about/userinfo.json
> +{
doesn't matter

2022-05-14 14:25 UTC, Oakchris1955 commented on init.js
> +function includeHTML() {
Make this yourself

2022-05-14 14:25 UTC, Oakchris1955 commented on init.js
> +			xhttp = new XMLHttpRequest();
fix it yourself instead of complaining

2022-05-14 14:59 UTC, moritz-t-w reviewed
It seems like a nice way of making our code less repetitive, tho it's a little rough around the edges. I will take a closer look later.

2022-05-14 15:01 UTC, splatterxl commented
@Oakchris1955 this is _your_ PR. I'm not going to fix your code for you

2022-05-14 15:04 UTC, Oakchris1955 commented
> It seems like a nice way of making our code less repetitive, tho it's a little rough around the edges. I will take a closer look later.

That is the whole point of this

2022-05-14 16:06 UTC, splatterxl commented
Updated for much better code style, haven't tested yet but should work fine

2022-05-14 16:10 UTC, splatterxl commented
okay wow this is broken

2022-05-14 16:12 UTC, moritz-t-w commented
> > It seems like a nice way of making our code less repetitive, tho it's a little rough around the edges. I will take a closer look later.
> 
> That is the whole point of this

yeah... I wasn't telling you that, I was just commenting that it's a nice way of achieving that point

2022-05-14 16:42 UTC, splatterxl commented
Alright folks! I've updated the script that loads the JS files as well as reorganising the entire repository.

**New changes**:
- assets should go in `/assets`, in their respective folder (this includes JS/CSS files but _not_ HTML)
- the user info JSON file has been moved to `/assets`, and the new format is as follows:

```json
{
	"username": "username/alias",
	"name": "previously firstName",
	"icon": "github:[github ID]",
	"alt": "alt text for icon",
	"bio": "text about yourself",
	"connections": [
		{
			"type": "github",
			"name": "your github slug"
		},
		{
			"type": "discord",
			"name": "discord tag (not ID)"
		}
	]
}
```

2022-05-15 10:39 UTC, Oakchris1955 commented
> okay wow this is broken

Just fixed it with afa5f427b029ba6bbc3de55677338ccd484b7058

2022-05-15 10:41 UTC, LukasDoesDev requested changes

2022-05-15 10:41 UTC, LukasDoesDev commented on assets/about.json
> +			"username": "Oakchris1955",
gay json

2022-05-15 11:05 UTC, Oakchris1955 reviewed
I'll bring those back once you are done

2022-05-15 11:47 UTC, splatterxl submitted a review, later dismissed

2022-05-15 11:47 UTC, splatterxl commented on assets/about.json
> +                "displayName": "SplatterXL",
```suggestion
                "displayName": "Splatter",
```

2022-05-15 11:47 UTC, splatterxl commented on assets/about.json
> +                    "spl&aumlt"
```suggestion
                    "spl&auml;t"
```

2022-05-15 11:47 UTC, splatterxl commented on assets/js/load_about.js
> +		switch (platform) {
add gitlab here

2022-05-15 11:55 UTC, splatterxl commented on assets/about.json
> +            "bio": "Originally a Discord bot developer, now I create small Rust applications.",
```suggestion
            "bio": "Avid learner and Rust, TypeScript, Elixir developer.",
```

2022-05-15 11:59 UTC, Oakchris1955 commented on assets/js/load_about.js
> +		switch (platform) {
wdym

2022-05-15 13:02 UTC, splatterxl commented
@moritz-t-w can you add gitlab & instagram to the `createConnection` function?

2022-05-15 13:56 UTC, splatterxl commented
this needs a rebase

2022-05-15 15:25 UTC, moritz-t-w commented
> @moritz-t-w can you add gitlab & instagram to the `createConnection` function?

Will do but later

2022-05-15 22:24 UTC, moritz-t-w approved these changes
Good to go

2022-05-15 22:29 UTC, merged

2022-05-16 07:24 UTC, splatterxl approved these changes

2022-05-16 07:24 UTC, splatterxl commented on assets/js/load_about.js
> +				elem.target = 'blank';
```suggestion
				elem.target = '_blank';
```

2022-05-16 07:24 UTC, splatterxl commented on assets/js/load_about.js
> +				elem.target = 'blank';
```suggestion
				elem.target = '_blank';
```